version: '3.9'

services:
  postgres:
    image: postgres:17.5-alpine
    container_name: omni_postgres_test
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - .env.test
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dev_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_password}
      POSTGRES_DB: ${POSTGRES_DB:-omni_test}
      TZ: America/Sao_Paulo
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - omni_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: omni_redis_test
    restart: always
    ports:
      - '${REDIS_PORT}:6379' # porta do host -> porta do container
    networks:
      - omni_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_test_data:

networks:
  omni_network:
    driver: bridge
